### ISSUE TITLE
Cannot open 15gb HydroShare resource using open with (nbfetch)

### ISSUE THREAD

**Issue by dtarb** [CUAHSI/jupyterhub#3]
I have a 15 GB resource that I would like to open in CUAHSI JupyterHub.  https://www.hydroshare.org/resource/bdbecdef23b14848b5da46c4f465ec21/. 

I get the following error from OpenWith
![image](https://user-images.githubusercontent.com/3456833/161598180-5dd9ebd1-d46e-4e66-8a08-5938a271252d.png)

15 GB is not large these days.

**Comment by dtarb** [comment]
Further info.  I left the window open and an hour later see 

![image](https://user-images.githubusercontent.com/3456833/161606787-e222f746-3296-4bb9-8d12-b11baba2805e.png)

Thus it is trying over and over.  I also see files being repeatedly updated (overwritten)

**Comment by aaraney** [comment]
There are a number of factors that could be causing this that may or may not be related to HydroShare "open with". Can you verify, @dtarb that you can download a zipped form of the resource from hydroshare.org? I think that is the first logical step to evaluate the issue origin.

**Comment by Castronova** [comment]
Another issue related to this would be the amount of user storage space that's provisioned in the JupyterHub cluster. By default all users on the CUAHSI JupyterHub as given 5Gb to store files.

Of course some of us, @dtarb included, have been given more space.

**Comment by dtarb** [comment]
I am able to download the zipped bag.

**Comment by aaraney** [comment]
Thanks for updating this @dtarb. Ill look into this more today and update the ticket with what ive explored.

**Comment by aaraney** [comment]
@dtarb, as Tony mentioned above:

> Another issue related to this would be the amount of user storage space that's provisioned in the JupyterHub cluster. 
> By default all users on the CUAHSI JupyterHub as given 5Gb to store files.
>
> Of course some of us, @dtarb included, have been given more space.

having looked into this more, I think the issue is related to the capacity of storage you have on CUAHSI JH and how much of that storage you have used. I have not looked into the kubernetes logs to confirm this, but checking the storage size your account has allocated on jupterhub(25gb) and the amount of storage you have used on CUAHSI's JH is ~11gb. The resource you referenced above is 20.8 gb in size, so I assume the resource cannot be opened using "open with" because you have run out of space.

**Comment by Castronova** [comment]
@dtarb As a short term fix, we can increase your JupyterHub storage quota. We'll have to think carefully about a longer term solution because holding onto large amounts of data is not something we want to get in the habit of...then again "large" is very subjective (25 GB is quite small these days). One thing that we've brainstormed in the past is implementing an automated data purge for accounts that have not been accessed in X days/months. Removing old data would enable us to justify providing larger quotas for active users. 

@aaraney, thoughts?

**Comment by aaraney** [comment]
As a short term "solution," I agree with you @Castronova. I also agree that we need to think of, and establish a data culling policy.
